name: Build and Release Binary

on:
  push:
    branches: [ main ]  # Trigger on pushes to the main branch
    tags:
      - 'v*'            # Trigger on version tags like 'v1.0.0'
  pull_request:
    branches: [ main ]
  workflow_dispatch:      # Allow manual triggering of the workflow

jobs:
  build:
    name: Build Binary
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'  # Specify Go version
      
      - name: Build Binary
        run: |
          mkdir -p build
          go build -o build/nesa2csv nesa2csv.go
          
      - name: List Generated Binary
        run: ls -lh build/
          
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nesa2csv
          path: build/nesa2csv
          retention-days: 7

  release:
    name: Create Release
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: nesa2csv
          path: build/
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/nesa2csv
          generate_release_notes: true